using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NETLectorAEBN49.Model
{
    public enum ConceptosComunesEnum : int
    {
        TALONES_REINTEGROS = 1,
        ABONARES_ENTREGAS_INGRESOS = 2,
        DOMICILIADOS_RECIBOS_LETRAS_PAGOSPORSUCUENTA = 3,
        GIROS_TRANSFERENCIAS_TRASPASOS_CHEQUES = 4,
        AMORTIZACIONESPRESTAMOS_CREDITOS_ETC = 5,
        REMESASEFECTOS = 6,
        SUSCRIPCIONES_DIVPASIVOS_CANJES = 7,
        DIVCUPONES_PRIMAJUNTA_AMORTIZACIONES = 8,
        OPERACIONESDEBOLSA_Y_O_COMPRAVENTAVALORES = 9,
        CHEQUESGASOLINA = 10,
        CAJEROAUTOMATICO = 11,
        TARJETASCREDITO_TARJETASDEBITO = 12,
        OPERACIONESEXTRANJERO = 13,
        DEVOLUCIONES_IMPAGADOS = 14,
        NOMINAS_SEGUROSSOCIALES = 15,
        TIMBRES_CORRETAJE_POLIZA = 16,
        INTERESES_COMISIONES_CUSTODIA_GASTOSEIMPUESTOS = 17,
        ANULACIONES_CORRECCIONESASIENTO = 98,
        VARIOS = 99
    }
}
